const m=(id,range,title,subtitle,goal,color,days,concepts,flow,quiz,choices,answer)=>({id,range,title,subtitle,goal,color,days,concepts,flow,quiz,choices,answer});
export const modules=[
 m('git','01 — 15','Git & GitHub','코드가 망가져도, 다시 돌아갈 수 있다.','AI의 변경을 검토하고 안전하게 복구','#c4f36b',[
 ['저장소','프로젝트를 담는 상자','프로젝트 파일을 저장소에 등록하고 변경 목록 확인'],['Commit','저장 시점 만들기','README를 변경하고 첫 커밋 만들기'],['Diff','바뀐 부분 읽기','AI가 바꾼 코드에서 추가·삭제 줄 찾기'],['Branch','안전한 실험 공간','feature 브랜치에서 제목 변경'],['Merge','실험 결과 합치기','검토한 브랜치를 main에 병합'],['Conflict','두 수정이 충돌하면','같은 줄을 다르게 수정하고 충돌 해결'],['Revert','이력을 남기며 되돌리기','잘못된 커밋을 되돌리는 새 커밋 생성'],['Restore','저장 전 수정 취소','커밋하지 않은 파일의 수정 취소'],['Reset','HEAD와 이력의 차이','soft·mixed·hard 차이를 실습용 저장소에서 비교'],['GitHub','원격 저장소','로컬과 원격 저장소의 관계 그리기'],['Pull request','변경 검토','작은 변경의 PR과 검토 기준 작성'],['작은 커밋','복구 가능한 단위','하나의 큰 변경을 3개 커밋으로 분리'],['AI 리뷰','AI 수정 통제','AI에게 diff 설명과 위험 지점 요청'],['복구 리허설','망가진 코드 복구','실습 브랜치의 오류를 되돌리고 정상 확인'],['최종 미션','Git으로 통제하기','분기 → 수정 → 검토 → 병합 → 복구 전 과정 수행']],
 [['Repository','코드와 이력을 담는 공간'],['Commit','변경을 저장한 체크포인트'],['Diff','이전과 현재의 차이'],['Branch','독립된 작업 흐름'],['Merge','서로 다른 흐름을 합침'],['Conflict','같은 부분의 수정 충돌'],['Rollback','이전 상태로 복구'],['Pull request','합치기 전 변경 검토']],['파일 변경','Diff 검토','Commit','Branch','Merge','복구'],'AI가 main에 잘못된 커밋을 이미 올렸다. 이력을 보존하며 취소하려면?',['git revert','git reset --hard 후 강제 push','저장소 삭제'],0),
 m('api','16 — 30','API & Network','서비스가 서로 대화하는 방법.','요청·응답과 인증 구조를 직접 설명','#6bb6ff',[
 ['연결 구조','사용자에서 DB까지','Frontend → API → Backend → DB 요청 그리기'],['HTTP','요청과 응답','URL·헤더·본문·응답 구조 읽기'],['GET','데이터 조회','실습 API에서 프로젝트 조회'],['POST','데이터 생성','JSON으로 새 프로젝트 생성'],['PUT / DELETE','수정과 삭제','전체 수정과 삭제의 상태 비교'],['JSON','데이터의 모양','문자열·숫자·배열·객체 구분'],['Status','응답 코드','200·201·400·401·404·429 구분'],['REST','리소스 설계','프로젝트와 문서의 경로 설계'],['API Key','비밀값 보호','서버의 환경변수에서 키를 읽도록 AI에 요청'],['환경변수','설정 분리','개발·운영 설정의 차이 표 작성'],['OAuth','접근 권한 위임','로그인 제공자와 서비스의 연결 흐름 그리기'],['JWT','서명된 토큰','토큰 검증·만료와 암호화의 차이 확인'],['CORS','브라우저의 출처 규칙','허용 출처와 인증의 차이 비교'],['Rate limit / Webhook','제한과 이벤트','호출 제한 및 결제 이벤트 처리 설계'],['최종 미션','API 문서 해석','실제 API 문서에서 URL·인증·제한·응답 표 작성']],
 [['GET / POST','조회 / 생성'],['PUT / DELETE','전체 수정 / 삭제'],['JSON','요청·응답 데이터 형식'],['HTTP status','요청 처리 결과'],['API Key','서버에서 보호할 인증값'],['OAuth / JWT','권한 위임 / 서명된 토큰'],['CORS','브라우저의 교차 출처 접근 규칙'],['Rate limit / Webhook','호출 제한 / 이벤트 알림']],['사용자','Frontend','HTTP 요청','Backend API','Database','JSON 응답'],'브라우저 코드에 외부 AI API의 비밀 키를 넣어도 될까?',['안 된다. 서버에서 환경변수로 관리','CORS를 설정하면 안전하다','JWT 문자열로 바꾸면 안전하다'],0),
 m('db','31 — 45','Database & Supabase','좋은 서비스는 좋은 데이터 구조에서 시작된다.','관계와 제약조건을 이해하고 DB 설계','#bb9bff',[
 ['Table','행과 열','사용자·프로젝트·문서 테이블 작성'],['SELECT','필요한 데이터 조회','전체 프로젝트 조회'],['WHERE','조건으로 좁히기','사용자 1의 프로젝트만 조회'],['INSERT','행 추가','새 프로젝트 추가'],['UPDATE / DELETE','행 변경','WHERE 유무에 따른 영향 비교'],['ORDER BY','순서 정하기','최근 프로젝트부터 정렬'],['JOIN','관계 연결','사용자와 프로젝트를 키로 연결'],['GROUP BY','묶어서 집계','사용자별 프로젝트 수 계산'],['Primary key','고유 식별','이름 대신 ID를 쓰는 이유 확인'],['Foreign key','관계의 무결성','존재하지 않는 사용자 참조 차단'],['1:N / N:N','관계의 종류','프로젝트와 팀원의 연결 테이블 설계'],['Index','검색 속도','조회가 빨라지는 대신 쓰기 비용이 늘어나는 이유 정리'],['Normalization','중복 줄이기','여러 행에 반복된 사용자 정보 분리'],['Transaction / RLS','일관성과 접근 제어','결제·권한 변경의 원자성과 행 접근 정책 설계'],['최종 미션','내 SaaS의 ERD','USER·PROJECT·DOCUMENT·AI_JOB·PAYMENT 관계 설계']],
 [['SELECT / WHERE','조회 / 조건'],['INSERT / UPDATE / DELETE','생성 / 수정 / 삭제'],['JOIN','테이블 관계 연결'],['ORDER BY / GROUP BY','정렬 / 묶어서 집계'],['PK / FK','고유 ID / 참조 ID'],['1:N / N:N','한 개 대 여러 개 / 다대다'],['Index / Normalization','검색 최적화 / 중복 분리'],['Transaction / RLS','한 묶음 처리 / 행 접근 정책']],['USER','PROJECT','DOCUMENT','AI_JOB','PAYMENT'],'프로젝트에 사용자의 이름을 복사해 두는 대신 user_id를 저장하는 이유는?',['관계를 연결하고 중복을 줄이려고','항상 검색이 더 빨라져서','암호화가 자동으로 적용돼서'],0),
 m('docker','46 — 55','Docker & Server','내 서버 위에, 내 서비스를 띄운다.','이미지·컨테이너·포트·볼륨으로 배포','#ffa873',[
 ['Image / Container','설계도와 실행 인스턴스','이미지 한 개로 컨테이너 두 개 실행 구조 비교'],['Dockerfile','이미지 만드는 방법','베이스 이미지·복사·실행 단계 읽기'],['Port','서비스 진입점','호스트 포트와 컨테이너 포트 연결'],['Environment','실행 설정','비밀값을 이미지에 넣지 않고 전달'],['Volume','데이터 보존','컨테이너 재시작 전후 데이터 비교'],['Compose','여러 서비스 실행','API·DB·Ollama 서비스 관계 구성'],['Log','실패 원인 추적','시작 실패와 요청 오류의 로그 구분'],['2.5G LAN','메인 PC와 세컨 PC','실제 IP·방화벽·포트 연결 확인'],['GPU 서비스','Ollama와 ComfyUI','GPU 공유·메모리 사용과 요청 대기 정리'],['최종 미션','세컨 PC 배포','API·AI·DB를 구분해 실행하고 재시작 검증']],
 [['Image','실행 환경과 코드의 묶음'],['Container','이미지의 실행 인스턴스'],['Dockerfile','이미지를 만드는 절차'],['Compose','여러 서비스의 실행 설정'],['Volume','컨테이너와 분리된 데이터'],['Port','외부와 내부 서비스 연결'],['Environment','실행 시 주입하는 설정'],['Log','실행 중 발생한 기록']],['메인 PC','2.5G LAN','세컨 PC','Docker','API / Ollama','DB / ComfyUI'],'DB 컨테이너를 교체해도 데이터를 보존하려면?',['볼륨에 데이터를 저장','컨테이너 이름을 같게 설정','포트 번호를 바꾸기'],0),
 m('arch','56 — 65','System Architecture','코드를 만들기 전에, 구조부터 그린다.','SaaS의 역할 분리와 비동기 처리 설계','#6ee7bc',[
 ['Requirements','필요한 행동','기능·사용자·완료 조건 정의'],['Frontend / Backend','화면과 처리','화면에서 할 일과 서버에서 할 일 분리'],['Database / Storage','구조 데이터와 파일','메타데이터와 영상 파일 저장 분리'],['Auth','인증과 권한','누구인가와 무엇을 할 수 있나 구분'],['Cache','반복 결과 재사용','캐시 갱신과 만료 기준 정하기'],['Queue / Worker','작업 대기와 처리','긴 AI 작업을 대기열과 worker로 분리'],['Sync / Async','기다림의 구조','30분 작업의 응답과 상태 조회 설계'],['API contracts','연결의 약속','요청·응답·실패 코드 표 작성'],['Test / Deploy','검증과 운영','실패·재시도·로그·배포 기준 설계'],['최종 미션','내 SaaS 구조도','요구사항 → DB → API → AI → UI → 테스트 → 배포']],
 [['Frontend','사용자가 조작하는 화면'],['Backend','규칙과 비밀값을 처리'],['Database / Storage','구조화 데이터 / 파일'],['Authentication','사용자 신원 확인'],['Cache','반복 요청 결과 재사용'],['Queue','긴 작업의 대기열'],['Worker','대기열 작업 실행'],['Sync / Async','기다려 응답 / 접수 후 별도 처리']],['요구사항','Architecture','Database','API + AI','Frontend','Test + Deploy'],'30분 걸리는 영상 생성 API는 어떻게 설계할까?',['작업 ID를 반환하고 Queue / Worker로 처리','HTTP 연결을 30분 동안 유지','프론트엔드에 GPU 코드를 넣기'],0),
 m('rag','66 — 75','LLM & RAG','AI가 답할 근거를, 내가 설계한다.','검색·근거·생성을 분리하고 RAG 비교','#f091c8',[
 ['Token / Context','입력의 크기','토큰 예산과 컨텍스트 제한 비교'],['Embedding','의미를 숫자로','문장 간 의미 유사도 비교'],['Chunking','검색 단위 만들기','작은 청크와 큰 청크의 차이 실습'],['Vector search','의미로 검색','질문에 가까운 문서 찾기'],['Reranking','검색 결과 재정렬','후보 중 관련성이 높은 근거 선별'],['RAG','근거를 붙여 생성','문서 → 검색 → 근거 → 답변 연결'],['Structured output','예측 가능한 결과','JSON schema와 필드 검증 정의'],['Tool calling','도구 선택','도구 요청과 실제 실행·권한 검증 분리'],['Temperature / Quantization','출력 다양성과 메모리','다양성·속도·메모리·품질의 교환 관계 정리'],['최종 미션','좋은 RAG vs 나쁜 RAG','같은 질문으로 근거 정확성과 모름 처리 비교']],
 [['Token / Context window','텍스트 단위 / 입력 한도'],['Embedding','의미를 표현한 벡터'],['Chunking','검색할 문서 단위 나누기'],['Vector search / Reranking','후보 검색 / 관련성 재정렬'],['RAG','검색 근거로 답변 생성'],['Structured output / Tool calling','출력 형식 / 도구 실행 요청'],['Hallucination / Temperature','근거 없는 생성 / 다양성 설정'],['Quantization','정밀도를 줄여 메모리 절약']],['문서','Chunk','Embedding','Vector DB','검색 + Rerank','근거 + LLM'],'검색된 문서에 질문의 답이 없을 때 가장 좋은 처리는?',['근거가 부족하다고 말하기','그럴듯한 답을 만들어 내기','Temperature를 높이면 정확해진다'],0),
 m('agent','76 — 83','Agent & MCP','AI를 늘리기 전에, 역할을 나눈다.','역할·도구·검증·승인 경계 설계','#f1d56c',[
 ['Agent 판단','정말 필요한가','고정 작업은 일반 코드, 판단 작업은 Agent 비교'],['Orchestrator','작업 분배','입력 → 계획 → 실행 → 검토 흐름 정의'],['Planner / Researcher','설계와 조사','계획 출력과 근거 수집의 책임 분리'],['Coder / Reviewer','구현과 검토','변경 내용과 검사 결과를 따로 기록'],['MCP','도구 연결의 계약','GitHub·DB·파일·브라우저 도구의 입출력 확인'],['Permissions','접근과 승인','읽기·쓰기·삭제·배포 권한 분리'],['Retry / Budget','실패와 비용 통제','재시도 횟수·시간·호출 예산 설정'],['최종 미션','Agent 워크플로','Planner → Coder → Reviewer → Test → Human 승인']],
 [['Orchestrator','진행 상태와 역할 분배'],['Planner','실행 계획 작성'],['Coder','계획에 따라 구현'],['Researcher','필요한 근거 조사'],['Reviewer','결과와 위험 검토'],['MCP','도구를 연결하는 프로토콜'],['Test','실행 결과 검증'],['Human 승인','중요 행동의 최종 결정']],['Orchestrator','Planner','Coder / Researcher','Reviewer','Test','Human 승인'],'매일 같은 CSV에서 합계를 계산하는 고정 작업은?',['일반 코드로 처리하는 것이 먼저','Agent 5개로 처리해야 정확하다','MCP 없이는 계산할 수 없다'],0),
 m('eval','84 — 90','Eval & Automation','느낌 대신, 숫자로 AI를 선택한다.','테스트 세트와 자동 검증으로 모델 선택','#82a5ff',[
 ['Test set','대표 작업 모으기','내 서비스의 대표 질문 100개 설계'],['Rubric','채점 기준','정확도·근거·형식의 합격 기준 정의'],['Metrics','여섯 개 지표','정확도·환각률·시간·비용·실패·재시도 측정'],['Model comparison','같은 조건 비교','클라우드 모델과 로컬 모델의 동일 테스트 비교'],['Failure / Retry','실패 분기','최대 재시도와 다른 모델 전환 기준'],['Automation','AI가 AI 검사','입력 → 작업 → 검사 → 실패 분기 → 승인 연결'],['최종 미션','90일 완성','내 SaaS 설계와 검증 결과를 한 장으로 정리']],
 [['Test set','대표 입력과 기대 결과'],['Accuracy','정답인 결과의 비율'],['Hallucination rate','근거 없는 답변의 비율'],['Latency / Cost','처리 시간 / 호출 비용'],['Failure / Retry rate','실패 비율 / 재시도 비율'],['Rubric','일관된 채점 기준'],['Fallback','실패 시 다른 처리 경로'],['Human 승인','검증 후 최종 승인']],['작업 입력','모델 선택','AI 작업','자동 검사','재시도 / 전환','Human 승인'],'모델 비교에서 가장 먼저 맞춰야 하는 것은?',['같은 입력과 같은 채점 기준','모델 이름의 인기','답변 길이만 동일하게'],0)
];
let offset=0;export const lessons=modules.flatMap((module,mi)=>module.days.map(([title,concept,task],li)=>({day:++offset,mi,li,title,concept,task})));
