import {missionGuides} from './mission-guides.js';
const m=(id,range,title,subtitle,goal,color,days,concepts,flow,quiz,choices,answer)=>({id,range,title,subtitle,goal,color,days,concepts,flow,quiz,choices,answer});
export const modules=[
 m('git','01 — 15','Git & GitHub','코드가 망가져도, 다시 돌아갈 수 있다.','AI의 변경을 검토하고 안전하게 복구','#c4f36b',[
 ['저장소','프로젝트를 담는 상자','저장소에서 파일 하나 찾기'],['Commit','저장 시점 만들기','제목 하나를 바꾸고 커밋으로 저장하기'],['Diff','바뀐 부분 읽기','바뀐 한 줄을 Diff에서 읽기'],['Branch','안전한 실험 공간','feature라는 연습 공간에서 제목 저장하기'],['Merge','실험 결과 합치기','검토한 feature 제목을 main에 합치기'],['Conflict','두 수정이 충돌하면','충돌한 제목 중 하나 선택하기'],['Revert','이력을 남기며 되돌리기','잘못 저장한 제목을 Revert로 되돌리기'],['Restore','저장 전 수정 취소','커밋 전 제목 수정을 취소하기'],['Reset','HEAD와 이력의 차이','Reset 세 종류의 차이를 표로 읽기'],['GitHub','원격 저장소','내 컴퓨터와 GitHub의 저장소 구분하기'],['Pull request','변경 검토','작은 변경의 PR 초안 쓰기'],['작은 커밋','복구 가능한 단위','큰 변경을 작은 커밋 계획으로 나누기'],['AI 리뷰','AI 수정 통제','AI의 한 줄 변경을 검토하기'],['복구 리허설','망가진 코드 복구','잘못된 제목을 복구하고 내용 확인하기'],['최종 미션','Git으로 통제하기','작은 Git 작업의 검토 기록 완성하기']],
 [['Repository','코드와 이력을 담는 공간'],['Commit','변경을 저장한 체크포인트'],['Diff','이전과 현재의 차이'],['Branch','독립된 작업 흐름'],['Merge','서로 다른 흐름을 합침'],['Conflict','같은 부분의 수정 충돌'],['Rollback','이전 상태로 복구'],['Pull request','합치기 전 변경 검토']],['파일 변경','Diff 검토','Commit','Branch','Merge','복구'],'AI가 main에 잘못된 커밋을 이미 올렸다. 이력을 보존하며 취소하려면?',['git revert','git reset --hard 후 강제 push','저장소 삭제'],0),
 m('api','16 — 30','API & Network','서비스가 서로 대화하는 방법.','요청·응답과 인증 구조를 직접 설명','#6bb6ff',[
 ['연결 구조','사용자에서 DB까지','상품 조회의 이동 경로 네 칸 쓰기'],['HTTP','요청과 응답','HTTP 요청과 응답 한 쌍 읽기'],['GET','데이터 조회','GET으로 가상 목록 조회하기'],['POST','데이터 생성','POST로 가상 항목 하나 만들기'],['PUT / DELETE','수정과 삭제','항목 하나 수정한 뒤 삭제 결과 확인하기'],['JSON','데이터의 모양','상품 JSON의 네 가지 값 구분하기'],['Status','응답 코드','응답 코드로 다음 행동 정하기'],['REST','리소스 설계','상품 REST 경로 두 개 정하기'],['API Key','비밀값 보호','비밀 API 키의 저장 위치 정하기'],['환경변수','설정 분리','개발 설정과 운영 설정 두 줄 구분하기'],['OAuth','접근 권한 위임','OAuth 로그인 흐름 네 단계 읽기'],['JWT','서명된 토큰','JWT를 비밀문이 아닌 확인표로 이해하기'],['CORS','브라우저의 출처 규칙','CORS와 인증의 차이 두 줄 쓰기'],['Rate limit / Webhook','제한과 이벤트','중복 결제 알림을 한 번만 처리하는 규칙 쓰기'],['최종 미션','API 문서 해석','작은 API 명세 한 장 읽기']],
 [['GET / POST','조회 / 생성'],['PUT / DELETE','전체 수정 / 삭제'],['JSON','요청·응답 데이터 형식'],['HTTP status','요청 처리 결과'],['API Key','서버에서 보호할 인증값'],['OAuth / JWT','권한 위임 / 서명된 토큰'],['CORS','브라우저의 교차 출처 접근 규칙'],['Rate limit / Webhook','호출 제한 / 이벤트 알림']],['사용자','Frontend','HTTP 요청','Backend API','Database','JSON 응답'],'브라우저 코드에 외부 AI API의 비밀 키를 넣어도 될까?',['안 된다. 서버에서 환경변수로 관리','CORS를 설정하면 안전하다','JWT 문자열로 바꾸면 안전하다'],0),
 m('db','31 — 45','Database & Supabase','좋은 서비스는 좋은 데이터 구조에서 시작된다.','관계와 제약조건을 이해하고 DB 설계','#bb9bff',[
 ['Table','행과 열','데이터를 행과 열로 나누기'],['SELECT','필요한 데이터 조회','SELECT로 세 행 읽기'],['WHERE','조건으로 좁히기','WHERE로 사용자 1의 기록만 읽기'],['INSERT','행 추가','INSERT로 가상 프로젝트 한 행 추가하기'],['UPDATE / DELETE','행 변경','WHERE를 붙여 한 행만 수정하기'],['ORDER BY','순서 정하기','ORDER BY로 큰 ID부터 읽기'],['JOIN','관계 연결','JOIN으로 사용자 이름과 프로젝트 연결하기'],['GROUP BY','묶어서 집계','GROUP BY로 사용자별 개수 세기'],['Primary key','고유 식별','이름 대신 고유 ID가 필요한 이유 쓰기'],['Foreign key','관계의 무결성','없는 사용자 번호를 참조하면 실패하는지 보기'],['1:N / N:N','관계의 종류','1:N 관계와 N:N 연결 표 구분하기'],['Index','검색 속도','Index의 이득과 비용 한 쌍 쓰기'],['Normalization','중복 줄이기','반복된 사용자 정보를 한 표로 분리하기'],['Transaction / RLS','일관성과 접근 제어','트랜잭션 취소와 접근 권한 구분하기'],['최종 미션','내 SaaS의 ERD','작은 서비스의 데이터 관계 세 개 그리기']],
 [['SELECT / WHERE','조회 / 조건'],['INSERT / UPDATE / DELETE','생성 / 수정 / 삭제'],['JOIN','테이블 관계 연결'],['ORDER BY / GROUP BY','정렬 / 묶어서 집계'],['PK / FK','고유 ID / 참조 ID'],['1:N / N:N','한 개 대 여러 개 / 다대다'],['Index / Normalization','검색 최적화 / 중복 분리'],['Transaction / RLS','한 묶음 처리 / 행 접근 정책']],['USER','PROJECT','DOCUMENT','AI_JOB','PAYMENT'],'프로젝트에 사용자의 이름을 복사해 두는 대신 user_id를 저장하는 이유는?',['관계를 연결하고 중복을 줄이려고','항상 검색이 더 빨라져서','암호화가 자동으로 적용돼서'],0),
 m('docker','46 — 55','Docker & Server','내 서버 위에, 내 서비스를 띄운다.','이미지·컨테이너·포트·볼륨으로 배포','#ffa873',[
 ['Image / Container','설계도와 실행 인스턴스','이미지와 컨테이너의 차이 두 줄 쓰기'],['Dockerfile','이미지 만드는 방법','Dockerfile 세 줄의 역할 읽기'],['Port','서비스 진입점','바깥 포트와 안쪽 포트 연결하기'],['Environment','실행 설정','실행할 때 전달할 설정 한 개 정하기'],['Volume','데이터 보존','볼륨이 기록을 남기는지 비교하기'],['Compose','여러 서비스 실행','Compose의 API와 DB 두 서비스 읽기'],['Log','실패 원인 추적','포트 충돌 로그에서 원인 하나 찾기'],['2.5G LAN','메인 PC와 세컨 PC','PC 두 대의 접속 확인 순서 쓰기'],['GPU 서비스','Ollama와 ComfyUI','GPU 작업 두 개가 메모리를 공유함을 이해하기'],['최종 미션','세컨 PC 배포','서버 교체 전 확인할 세 칸 쓰기']],
 [['Image','실행 환경과 코드의 묶음'],['Container','이미지의 실행 인스턴스'],['Dockerfile','이미지를 만드는 절차'],['Compose','여러 서비스의 실행 설정'],['Volume','컨테이너와 분리된 데이터'],['Port','외부와 내부 서비스 연결'],['Environment','실행 시 주입하는 설정'],['Log','실행 중 발생한 기록']],['메인 PC','2.5G LAN','세컨 PC','Docker','API / Ollama','DB / ComfyUI'],'DB 컨테이너를 교체해도 데이터를 보존하려면?',['볼륨에 데이터를 저장','컨테이너 이름을 같게 설정','포트 번호를 바꾸기'],0),
 m('arch','56 — 65','System Architecture','코드를 만들기 전에, 구조부터 그린다.','SaaS의 역할 분리와 비동기 처리 설계','#6ee7bc',[
 ['Requirements','필요한 행동','가상 상품 소개 기능의 완료 조건 하나 쓰기'],['Frontend / Backend','화면과 처리','화면과 서버의 할 일 나누기'],['Database / Storage','구조 데이터와 파일','상품 정보와 이미지 파일 저장 위치 나누기'],['Auth','인증과 권한','로그인 확인과 수정 권한 구분하기'],['Cache','반복 결과 재사용','캐시한 가격을 언제 갱신할지 정하기'],['Queue / Worker','작업 대기와 처리','긴 AI 작업을 접수와 처리로 나누기'],['Sync / Async','기다림의 구조','비동기 접수와 작업 완료 시간 구분하기'],['API contracts','연결의 약속','AI 작업 요청·응답 약속 쓰기'],['Test / Deploy','검증과 운영','정상과 실패를 확인할 체크 두 개 쓰기'],['최종 미션','내 SaaS 구조도','작은 상품 소개 서비스 구조 한 장 완성하기']],
 [['Frontend','사용자가 조작하는 화면'],['Backend','규칙과 비밀값을 처리'],['Database / Storage','구조화 데이터 / 파일'],['Authentication','사용자 신원 확인'],['Cache','반복 요청 결과 재사용'],['Queue','긴 작업의 대기열'],['Worker','대기열 작업 실행'],['Sync / Async','기다려 응답 / 접수 후 별도 처리']],['요구사항','Architecture','Database','API + AI','Frontend','Test + Deploy'],'30분 걸리는 영상 생성 API는 어떻게 설계할까?',['작업 ID를 반환하고 Queue / Worker로 처리','HTTP 연결을 30분 동안 유지','프론트엔드에 GPU 코드를 넣기'],0),
 m('rag','66 — 75','LLM & RAG','AI가 답할 근거를, 내가 설계한다.','검색·근거·생성을 분리하고 RAG 비교','#f091c8',[
 ['Token / Context','입력의 크기','긴 입력을 필요한 문장 두 개로 줄이기'],['Embedding','의미를 숫자로','표현이 달라도 뜻이 비슷한 문장 묶기'],['Chunking','검색 단위 만들기','청크가 작아지면 조건이 끊기는지 보기'],['Vector search','의미로 검색','질문에 맞는 검색 근거 하나 고르기'],['Reranking','검색 결과 재정렬','검색 후보가 질문에 답하는지 다시 확인하기'],['RAG','근거를 붙여 생성','근거가 없는 질문에 모른다고 하기'],['Structured output','예측 가능한 결과','AI 결과를 JSON 두 필드로 요청하기'],['Tool calling','도구 선택','도구 요청과 실제 실행을 나누기'],['Temperature / Quantization','출력 다양성과 메모리','Temperature와 Quantization 목적 구분하기'],['최종 미션','좋은 RAG vs 나쁜 RAG','좋은 RAG의 검사 기준 두 개 남기기']],
 [['Token / Context window','텍스트 단위 / 입력 한도'],['Embedding','의미를 표현한 벡터'],['Chunking','검색할 문서 단위 나누기'],['Vector search / Reranking','후보 검색 / 관련성 재정렬'],['RAG','검색 근거로 답변 생성'],['Structured output / Tool calling','출력 형식 / 도구 실행 요청'],['Hallucination / Temperature','근거 없는 생성 / 다양성 설정'],['Quantization','정밀도를 줄여 메모리 절약']],['문서','Chunk','Embedding','Vector DB','검색 + Rerank','근거 + LLM'],'검색된 문서에 질문의 답이 없을 때 가장 좋은 처리는?',['근거가 부족하다고 말하기','그럴듯한 답을 만들어 내기','Temperature를 높이면 정확해진다'],0),
 m('agent','76 — 83','Agent & MCP','AI를 늘리기 전에, 역할을 나눈다.','역할·도구·검증·승인 경계 설계','#f1d56c',[
 ['Agent 판단','정말 필요한가','규칙 고정 작업에 Agent가 필요한지 판단하기'],['Orchestrator','작업 분배','진행 담당자와 실행 담당자 구분하기'],['Planner / Researcher','설계와 조사','계획과 근거 조사 결과를 분리하기'],['Coder / Reviewer','구현과 검토','구현 내용과 검사 결과를 따로 기록하기'],['MCP','도구 연결의 계약','MCP 도구의 입력과 출력을 한 쌍 쓰기'],['Permissions','접근과 승인','쓰기 권한이 없으면 작업이 멈추는지 확인하기'],['Retry / Budget','실패와 비용 통제','실패 재시도를 한 번으로 제한하기'],['최종 미션','Agent 워크플로','검사 후 사람이 승인하는 흐름 끝내기']],
 [['Orchestrator','진행 상태와 역할 분배'],['Planner','실행 계획 작성'],['Coder','계획에 따라 구현'],['Researcher','필요한 근거 조사'],['Reviewer','결과와 위험 검토'],['MCP','도구를 연결하는 프로토콜'],['Test','실행 결과 검증'],['Human 승인','중요 행동의 최종 결정']],['Orchestrator','Planner','Coder / Researcher','Reviewer','Test','Human 승인'],'매일 같은 CSV에서 합계를 계산하는 고정 작업은?',['일반 코드로 처리하는 것이 먼저','Agent 5개로 처리해야 정확하다','MCP 없이는 계산할 수 없다'],0),
 m('eval','84 — 90','Eval & Automation','느낌 대신, 숫자로 AI를 선택한다.','테스트 세트와 자동 검증으로 모델 선택','#82a5ff',[
 ['Test set','대표 작업 모으기','대표 질문 세 개로 테스트 세트 만들기'],['Rubric','채점 기준','답변 합격 기준 두 개 정하기'],['Metrics','여섯 개 지표','정확도와 처리 시간 두 지표 읽기'],['Model comparison','같은 조건 비교','같은 조건으로 모델 두 개 비교하기'],['Failure / Retry','실패 분기','기준 미달이면 전환하거나 멈추는지 보기'],['Automation','AI가 AI 검사','자동 검사 뒤 사람 확인 지점 쓰기'],['최종 미션','90일 완성','가상 상품 소개 서비스의 검토 한 장 완성하기']],
 [['Test set','대표 입력과 기대 결과'],['Accuracy','정답인 결과의 비율'],['Hallucination rate','근거 없는 답변의 비율'],['Latency / Cost','처리 시간 / 호출 비용'],['Failure / Retry rate','실패 비율 / 재시도 비율'],['Rubric','일관된 채점 기준'],['Fallback','실패 시 다른 처리 경로'],['Human 승인','검증 후 최종 승인']],['작업 입력','모델 선택','AI 작업','자동 검사','재시도 / 전환','Human 승인'],'모델 비교에서 가장 먼저 맞춰야 하는 것은?',['같은 입력과 같은 채점 기준','모델 이름의 인기','답변 길이만 동일하게'],0)
];
let offset=0;export const lessons=modules.flatMap((module,mi)=>module.days.map(([title,concept,task],li)=>{const day=++offset,guide=missionGuides[day-1];return {day,mi,li,title,concept,task:guide.goal,guide}}));
