import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{gsap}from'gsap';
import * as THREE from 'three';
import{Terminal,GitBranch,Globe,Database,Container,Layers,BrainCircuit,Workflow,ChartNoAxesCombined,Check,Play,Pause,RotateCcw,ChevronRight,PanelLeftClose,PanelLeftOpen,Target,Clock,CheckCircle2,BookOpen,FlaskConical,ArrowUpRight,Download,Focus,Volume2,X}from'lucide-react';
import{modules,lessons}from'./curriculum';
import{Lab}from'./labs';
import {MissionSummary,MissionGuide} from './mission-ui';
import {readState,STORAGE_KEY} from './learning-state';
import './style.css';
const icons=[GitBranch,Globe,Database,Container,Layers,BrainCircuit,Workflow,ChartNoAxesCombined];
function Network({color}){const ref=useRef();useEffect(()=>{const el=ref.current;let renderer,frame,observer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.z=7;const group=new THREE.Group();scene.add(group);const positions=[];for(let i=0;i<14;i++){const a=i*2.399963,r=1.8*Math.sqrt(i/14);positions.push(new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r,Math.sin(i*1.7)*.8))}const geo=new THREE.IcosahedronGeometry(.065,1),mat=new THREE.MeshBasicMaterial({color});positions.forEach(p=>{const mesh=new THREE.Mesh(geo,mat);mesh.position.copy(p);group.add(mesh)});const lineGeo=new THREE.BufferGeometry().setFromPoints(positions.flatMap((p,i)=>positions.slice(i+1).filter(q=>p.distanceTo(q)<1.9).flatMap(q=>[p,q])));const lineMat=new THREE.LineBasicMaterial({color,transparent:true,opacity:.26});group.add(new THREE.LineSegments(lineGeo,lineMat));const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()};resize();observer=new ResizeObserver(resize);observer.observe(el);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const draw=()=>{if(!reduced){group.rotation.y+=.002;group.rotation.z+=.0005}renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(frame);observer.disconnect();geo.dispose();mat.dispose();lineGeo.dispose();lineMat.dispose();renderer.dispose();renderer.domElement.remove()}}catch{el.innerHTML='<span class="network-fallback">◇ · ◇ · ◇</span>';return()=>{renderer?.dispose()}}},[color]);return <div ref={ref} className="network" aria-hidden="true"/>}
function Flow({items}){return <div className="flow">{items.map((x,i)=><React.Fragment key={x}><div className="flow-node"><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></div>{i<items.length-1&&<ChevronRight size={17}/>}</React.Fragment>)}</div>}
function Timer(){const[sec,S]=useState(600),[running,R]=useState(false),[phase,P]=useState(10);useEffect(()=>{if(!running||sec<=0){if(sec===0)R(false);return}const id=setInterval(()=>S(x=>x-1),1000);return()=>clearInterval(id)},[running,sec]);return <div className="timer"><Clock size={16}/><button onClick={()=>{P(phase===10?15:10);S(phase===10?900:600);R(false)}}>집중 {phase}분</button><b>{String(Math.floor(sec/60)).padStart(2,'0')}:{String(sec%60).padStart(2,'0')}</b><button aria-label={running?'타이머 일시정지':'타이머 시작'} onClick={()=>R(!running)}>{running?<Pause size={15}/>:<Play size={15}/>}</button><button aria-label="타이머 초기화" onClick={()=>{S(phase*60);R(false)}}><RotateCcw size={14}/></button></div>}
function App(){const initial=useRef(readState()).current;const[day,D]=useState(initial.day||1),[completed,C]=useState(initial.completed||[]),[notes,N]=useState(initial.notes||{}),[tab,T]=useState('learn'),[focus,F]=useState(false),[menu,M]=useState(false),[quiz,Q]=useState(null),[checked,K]=useState([]),[status,S]=useState('');const lesson=lessons[day-1],mod=modules[lesson.mi],Icon=icons[lesson.mi],content=useRef();const total=completed.length,percent=Math.round(total/90*100);useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({day,completed,notes}));}catch{S('브라우저 저장 공간이 부족합니다. 기록 내보내기를 이용하세요.')}},[day,completed,notes]);useEffect(()=>{K([])},[day]);useEffect(()=>{Q(null);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const ctx=gsap.context(()=>gsap.fromTo('.animate-in',{opacity:0,y:12},{opacity:1,y:0,duration:.45,stagger:.055,ease:'power2.out'}),content);return()=>ctx.revert()}},[day,tab]);useEffect(()=>{const c=document.modelContext;if(!c?.registerTool)return;const life=new AbortController();for(const tool of[{name:'read_learning_progress',description:'이 브라우저의 현재 학습일과 완료일을 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>readState()},{name:'navigate_learning_day',description:'1부터 90 사이의 학습일로 이동합니다. 완료 처리하지 않습니다.',inputSchema:{type:'object',properties:{day:{type:'integer',minimum:1,maximum:90}},required:['day'],additionalProperties:false},execute:async input=>{if(!Number.isInteger(input.day)||input.day<1||input.day>90)throw new Error('day must be 1–90');D(input.day);T('learn');await new Promise(r=>setTimeout(r,0));return{day:input.day,title:lessons[input.day-1].title}}}]){try{Promise.resolve(c.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}return()=>life.abort()},[]);function select(n){D(n);T('learn');M(false)}function finish(){C(a=>a.includes(day)?a:[...a,day]);S(`DAY ${day} 완료. 잘하셨습니다.`)}function exportNotes(){const blob=new Blob([JSON.stringify({version:1,day,completed,notes},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='build90-learning.json';a.click();URL.revokeObjectURL(url)}return <div className={`app ${focus?'focus-mode':''}`} style={{'--accent':mod.color}}>
 <aside className={`sidebar ${menu?'is-open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();select(1)}}><span className="brand-symbol"><Terminal size={22}/></span><b>BUILD<span>/90</span></b></a><div className="sidebar-caption">AI DEVELOPER WORKSPACE</div><div className="side-progress"><div><span>나의 학습 여정</span><b>{percent}%</b></div><div className="progress-track"><i style={{width:percent+'%'}}/></div><small>{total} / 90일 완료</small></div><div className="nav-label">CURRICULUM <span>8 MODULES</span></div><nav>{modules.map((m,i)=>{const I=icons[i],ds=lessons.filter(x=>x.mi===i),n=ds.filter(x=>completed.includes(x.day)).length;return <button key={m.id} className={`nav-module ${i===lesson.mi?'selected':''}`} onClick={()=>select(ds[0].day)} style={{'--module-color':m.color}}><I size={18}/><div><strong>{m.title}</strong><small>DAY {m.range}</small></div>{n===ds.length?<CheckCircle2 size={16}/>:<span className="nav-index">{String(i+1).padStart(2,'0')}</span>}</button>})}</nav><div className="sidebar-bottom"><div className="avatar">B</div><div><b>Builder</b><small>구조를 이해하는 개발자</small></div><button title="학습 기록 내보내기" aria-label="학습 기록 내보내기" onClick={exportNotes}><Download size={16}/></button></div></aside>
 {menu&&<button className="overlay" aria-label="메뉴 닫기" onClick={()=>M(false)}/>}
 <main ref={content}><header className="topbar"><div className="breadcrumb"><button className="mobile-menu" aria-label="과정 메뉴" onClick={()=>M(!menu)}><PanelLeftOpen size={20}/></button><span>학습 워크스페이스</span><ChevronRight size={14}/><b>{mod.title}</b></div><div className="top-actions"><span className="local-label">이 기기에 기록 저장</span><button className={`focus-button ${focus?'on':''}`} onClick={()=>F(!focus)}><Focus size={16}/>{focus?'전체 보기':'집중 모드'}</button></div></header>
 <div className="workspace"><section className="course-header animate-in"><div className="course-heading"><div className="eyebrow"><span className="pill">MODULE {String(lesson.mi+1).padStart(2,'0')}</span><span>DAY {mod.range}</span></div><h1>{mod.title}<span className="heading-dot">.</span></h1><p>{mod.subtitle}</p><div className="course-meta"><span><Target size={15}/>{mod.goal}</span><span><Clock size={15}/>기본 10~15분 · 심화 선택</span></div></div><Network color={mod.color}/></section>
 <section className="summary-strip animate-in"><div><span>현재 학습일</span><strong>DAY {String(day).padStart(2,'0')}<small> / 90</small></strong></div><div><span>이번 과정</span><strong>{lessons.filter(l=>l.mi===lesson.mi&&completed.includes(l.day)).length}<small> / {mod.days.length} 완료</small></strong></div><div><span>오늘의 리듬</span><strong>{lesson.guide.minutes} <small>분 작은 실습</small></strong></div><div className="summary-next"><span>최종 목표</span><strong>AI에게 맡기고, 구조는 내가 통제</strong></div></section>
 <div className="work-grid"><section className="learning-panel animate-in"><div className="panel-top"><div className="section-title"><span className="square-icon"><Icon size={18}/></span><div><small>TODAY'S MISSION</small><h2>{lesson.title}</h2></div></div><span className="day-label">DAY {String(day).padStart(2,'0')}</span></div><div className="day-navigation"><button className="secondary" disabled={day===1} onClick={()=>select(day-1)}>이전 미션</button><span>DAY {day} / 90</span><button className="secondary" disabled={day===90} onClick={()=>select(day+1)}>다음 미션</button></div><div className="tabs" role="tablist" aria-label="학습 보기">{[['learn','오늘 할 일',BookOpen],['lab','작은 실습 시작',FlaskConical],['check','성공 확인',CheckCircle2]].map(([id,label,I])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>T(id)} className={tab===id?'active':''}><I size={15}/>{label}</button>)}</div>
 <div className="tab-body animate-in">{tab==='learn'?<>
 <MissionSummary guide={lesson.guide}/>
 <button className="primary" onClick={()=>T('lab')}><FlaskConical size={16}/>작은 실습 시작</button>
 <details className="optional-details"><summary>선택 참고 · 이 과정의 전체 구조와 용어</summary><Flow items={mod.flow}/><div className="table-wrapper"><table className="concept-table"><thead><tr><th>핵심 개념</th><th>쉬운 설명</th></tr></thead><tbody>{mod.concepts.map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div></details>
 </>:tab==='lab'?<>
 <MissionGuide guide={lesson.guide}/>
 <details key={day} className="practice-details" open={lesson.guide.simulator}><summary>{lesson.guide.simulator?'오늘의 연습 화면':'선택 참고 · 이 과정의 연습 화면'}</summary><div className="lab-notice"><FlaskConical size={14}/>{mod.id==='db'?'실습용 SQLite · 실제 고객정보 없음':'브라우저 안의 학습 모형 · 실제 앱 조작 없음'}</div><Lab key={`${mod.id}-${day}`} id={mod.id} day={day}/></details>
 <label className="note-label" htmlFor="learning-note">실습 기록 <span>직접 확인한 결과 한 줄이면 충분합니다</span></label><textarea id="learning-note" value={notes[day]||''} onChange={e=>N({...notes,[day]:e.target.value})} placeholder={lesson.guide.result+' — 확인한 내용을 적으세요.'}/>
 <button className="primary" onClick={()=>T('check')}>성공 확인으로 이동</button>
 </>:<>
 <div className="lesson-intro"><span className="tiny-label">오늘의 성공 기준</span><h3>{lesson.guide.goal}</h3><p>AI의 설명만으로 완료하지 마세요. 아래 결과를 직접 확인하고 표시해 주세요.</p></div>
 <div className="success-checks">{lesson.guide.checks.map((check,i)=><label key={check}><input type="checkbox" checked={checked.includes(i)} onChange={e=>K(a=>e.target.checked?[...a,i]:a.filter(n=>n!==i))}/><span>{check}</span></label>)}</div>
 <p className="small-scope">기대 결과: {lesson.guide.result}</p>
 <div className="complete-actions"><button className="primary" disabled={checked.length!==lesson.guide.checks.length} onClick={finish}><Check size={16}/>{completed.includes(day)?'완료 기록됨':'오늘 학습 완료'}</button><button className="secondary" onClick={()=>T('lab')}>실습 다시 보기</button>{completed.includes(day)&&day<90&&<button className="secondary" onClick={()=>select(day+1)}>다음 학습일</button>}</div>
 <details className="optional-details"><summary>선택 복습 · 과정 전체 이해도 질문</summary><div className="lesson-intro"><h3>{mod.quiz}</h3></div><div className="quiz-options">{mod.choices.map((choice,i)=><button className={quiz===i?(i===mod.answer?'correct':'incorrect'):''} onClick={()=>Q(i)} key={choice}><span>{String(i+1).padStart(2,'0')}</span>{choice}{quiz===i&&(i===mod.answer?<Check size={18}/>:<X size={18}/>)}</button>)}</div>{quiz!==null&&<div className={`feedback ${quiz===mod.answer?'success':'error'}`} role="status">{quiz===mod.answer?'맞습니다. 과정 전체를 복습하셨습니다.':'개념 표를 참고해서 다시 생각해 보세요.'}</div>}</details>
 </>}</div></section>
 <aside className="right-rail animate-in"><section className="journey-card"><div className="section-row"><h2>학습 지도</h2><span>{mod.days.length} DAYS</span></div><div className="days-grid">{lessons.filter(x=>x.mi===lesson.mi).map(l=><button key={l.day} title={`DAY ${l.day} · ${l.title}`} aria-label={`DAY ${l.day} ${l.title}`} className={`${day===l.day?'current':''} ${completed.includes(l.day)?'done':''}`} onClick={()=>select(l.day)}>{completed.includes(l.day)?<Check size={17}/>:String(l.day).padStart(2,'0')}</button>)}</div><div className="day-legend"><span><i className="current-key"/>현재</span><span><i className="done-key"/>완료</span><span><i/>예정</span></div><div className="rail-rule"/><span className="tiny-label">지금 배우는 것</span><h3>{lesson.title}</h3><p>{lesson.concept}</p><Timer/></section><section className="skill-card"><div className="section-row"><h2>과정별 진행</h2><ChartNoAxesCombined size={17}/></div>{modules.map((m,i)=>{const ls=lessons.filter(l=>l.mi===i),pc=Math.round(ls.filter(l=>completed.includes(l.day)).length/ls.length*100);return <div className="skill-row" key={m.id}><div><span>{m.title.split(' & ')[0]}</span><b>{pc}%</b></div><div className="skill-track"><i style={{width:pc+'%',background:m.color}}/></div></div>})}<small>완료한 날짜 기준 · 숙련도 평가와 다릅니다</small></section><div className="learning-principle"><span>THE BUILDER MINDSET</span><p>문법을 외우기보다<br/><b>구조를 이해하고 통제하기.</b></p></div></aside></div>
 <section className="roadmap-section animate-in"><div className="section-row"><div><span className="tiny-label">YOUR 90-DAY ROADMAP</span><h2>작게 실습하고, 큰 구조를 완성하세요.</h2></div><span>8개 과정 · 90개 미션</span></div><div className="roadmap-grid">{modules.map((m,i)=>{const I=icons[i];return <button className={`roadmap-card ${i===lesson.mi?'selected':''}`} key={m.id} onClick={()=>select(lessons.find(l=>l.mi===i).day)} style={{'--card-color':m.color}}><div><I size={21}/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{m.title}</h3><span>DAY {m.range}</span><p>{m.goal}</p></button>})}</div></section><footer><span>BUILD / 90</span><p>Git → API → DB → Docker → Architecture → RAG → Agent → Eval</p><button onClick={exportNotes}><Download size={14}/>기록 내보내기</button></footer></div></main>{status&&<div className="toast" role="status"><CheckCircle2 size={17}/>{status}<button aria-label="알림 닫기" onClick={()=>S('')}><X size={14}/></button></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
